### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by xujiajie1997** [eborghi10/jps_global_planner#5]
In which file is this parameter set?--------

JumpPointSearchROS:
  debug: true

thanks

**Comment by eborghi10** [comment]
That's part of the usage as global planner: https://github.com/RoboticaUtnFrba/create_autonomy/blob/kinetic-devel/navigation/ca_move_base/config/jps_global_planner_params.yaml

**Comment by xujiajie1997** [comment]
<rosparam file="$(find ca_move_base)/config/jps_global_planner.yaml" command="load" /> 
Is it like this？
thanks！

**Comment by xujiajie1997** [comment]
‘<rosparam file="$(find ca_move_base)/config/jps_global_planner.yaml" command="load" /> ’
Is it like this？thanks

**Comment by xujiajie1997** [comment]
rosparam file="$(find xxx)/xxx/jps_global_planner.yaml" command="load" /
Is it like this？thanks

**Comment by eborghi10** [comment]
Exactly.

**Comment by eborghi10** [comment]
Check here: https://github.com/RoboticaUtnFrba/create_autonomy/blob/kinetic-devel/navigation/ca_move_base/launch/move_base.launch#L31

**Comment by xujiajie1997** [comment]
thanks！



发自我的iPhone


------------------ Original ------------------
From: Emiliano Borghi ***@***.***&gt;
Date: Thu,May 12,2022 1:59 AM
To: eborghi10/jps_global_planner ***@***.***&gt;
Cc: xujiajie1997 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [eborghi10/jps_global_planner] problem (Issue #5)





 
Check here: https://github.com/RoboticaUtnFrba/create_autonomy/blob/kinetic-devel/navigation/ca_move_base/launch/move_base.launch#L31
